---
- name: MSSQL-Server-Container mit Agent-Backup-Job deployen
  hosts: mssql_servers
  become: true

  roles:
    - role: docker_engine
    - role: wireguard_server
    - role: mssql_docker
    - role: docker_cleanup
    - role: sftp_backup
    - role: ssh_allowlist
